# HTML report (core spec v0.1, spec/reporting/report-structure.md).
# Self-contained file, no external assets. Section order is the argument:
# structure, then ledger, then estimate, then attacks, then decision.

esc <- function(x) {
  x <- gsub("&", "&amp;", as.character(x), fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  gsub(">", "&gt;", x, fixed = TRUE)
}

fmt <- function(x, d = 3) formatC(x, format = "f", digits = d)

verdict_chip <- function(v) {
  cls <- c(stable = "ok", unstable = "bad", not_resolvable = "nr")[v]
  lab <- c(stable = "stable", unstable = "unstable",
           not_resolvable = "not resolvable at this n")[v]
  sprintf('<span class="chip %s">%s</span>', cls, lab)
}

# A small Hasse diagram of the pooling lattice: nodes by level (how much is
# pooled), edges add one pooled axis, coloured by status.
lattice_svg <- function(L) {
  fill <- c(consistent = "#2e6e4e", attenuated = "#8a6d1f", reversed = "#a33d2e")
  k <- length(L$axes)
  nds <- L$nodes
  W <- 540; H <- 60 + k * 90; pad <- 34
  lev <- vapply(nds, function(x) x$n_pooled, integer(1))
  pos <- vector("list", length(nds))
  for (idx in seq_along(nds)) {
    row_idx <- which(lev == lev[idx]); m <- length(row_idx); i <- match(idx, row_idx)
    y <- H - pad - lev[idx] * ((H - 2 * pad) / max(k, 1))
    x <- if (m == 1) W / 2 else pad + (i - 1) * (W - 2 * pad) / (m - 1)
    pos[[idx]] <- list(x = x, y = y, pooled = sort(unlist(nds[[idx]]$pooled)),
                       status = nds[[idx]]$status, est = nds[[idx]]$estimate)
  }
  edges <- ""
  for (a in seq_along(pos)) for (b in seq_along(pos)) {
    pa <- pos[[a]]$pooled; pb <- pos[[b]]$pooled
    if (length(pb) == length(pa) + 1 && all(pa %in% pb))
      edges <- paste0(edges, sprintf("<line x1='%.0f' y1='%.0f' x2='%.0f' y2='%.0f' stroke='#c7ccd3'/>",
                                     pos[[a]]$x, pos[[a]]$y, pos[[b]]$x, pos[[b]]$y))
  }
  circles <- ""
  for (p in pos) {
    lab <- if (length(p$pooled) == 0) "none" else paste(substr(p$pooled, 1, 4), collapse = "+")
    circles <- paste0(circles,
      sprintf("<circle cx='%.0f' cy='%.0f' r='17' fill='%s'/><text x='%.0f' y='%.0f' text-anchor='middle' font-size='8' fill='#fff'>%s</text><text x='%.0f' y='%.0f' text-anchor='middle' font-size='9' fill='#5b6673'>%s</text>",
              p$x, p$y, fill[[p$status]], p$x, p$y + 2, esc(lab), p$x, p$y + 32, fmt(p$est, 2)))
  }
  sprintf("<svg viewBox='0 0 %d %d' width='100%%' style='max-width:540px'>%s%s</svg>", W, H, edges, circles)
}

limitations_paragraph <- function(audit) {
  d <- audit$decision
  base <- switch(d$status,
    proceed = paste0(
      "The invariance assumptions relied on for pooling (",
      paste(gsub("_", " ", d$load_bearing), collapse = "; "),
      ") were each attacked by transformation tests and came back stable at the precision the data allowed."),
    conditional = paste0(
      "The following invariance assumptions were relied on but could not be assessed, or were not resolvable at this sample size: ",
      paste(gsub("_", " ", d$exposed_surface), collapse = "; "),
      ". Conclusions are conditional on these claims holding."),
    abstain = paste0(
      "The analysis abstains from a pooled conclusion: the ", d$broken_by,
      " attack showed that a relied-on invariance does not hold up, and the pooling it licenses has no basis in this data."))
  paste0(base, " Stability verdicts assess whether the conclusion survived the attacks that were run;",
         " they do not establish the truth of the assumptions.",
         " [Draft for the analyst to edit; generated by assesslite, core spec 0.1.]")
}

#' Render the audit as a self-contained HTML report
#'
#' @param audit a structural_audit object after `decide()`.
#' @param path file path to write the HTML report to.
#' @return the path, invisibly.
render_report <- function(audit, path) {
  a <- audit$analysis; s <- audit$structure; e <- audit$estimate; d <- audit$decision
  if (is.null(d)) stop("run decide() before rendering; a report without a decision is not complete")
  al <- audit_as_list(audit)

  css <- "
  :root { --ink:#1a2330; --muted:#5b6673; --line:#d9dde3; --bg:#fafaf8; --card:#ffffff;
          --accent:#33586e; --ok:#2e6e4e; --bad:#a33d2e; --nr:#8a6d1f; }
  body { font: 15px/1.55 'Avenir Next', 'Segoe UI', system-ui, sans-serif;
         color: var(--ink); background: var(--bg); margin: 0; }
  main { max-width: 860px; margin: 0 auto; padding: 40px 24px 80px; }
  h1 { font-size: 1.5rem; font-weight: 600; margin: 0 0 4px; }
  h2 { font-size: 1.05rem; font-weight: 600; margin: 36px 0 10px; color: var(--accent);
       text-transform: lowercase; letter-spacing: .02em; }
  .meta { color: var(--muted); font-size: .85rem; }
  table { border-collapse: collapse; width: 100%; font-size: .9rem; background: var(--card); }
  th, td { text-align: left; padding: 7px 10px; border-bottom: 1px solid var(--line); vertical-align: top; }
  th { color: var(--muted); font-weight: 600; font-size: .8rem; }
  .chip { display: inline-block; padding: 1px 9px; border-radius: 10px; font-size: .8rem;
          color: #fff; white-space: nowrap; }
  .chip.ok { background: var(--ok); } .chip.bad { background: var(--bad); } .chip.nr { background: var(--nr); }
  .decision { border-left: 4px solid var(--accent); background: var(--card);
              padding: 14px 18px; margin-top: 8px; }
  .decision.abstain { border-color: var(--bad); } .decision.proceed { border-color: var(--ok); }
  .decision.conditional { border-color: var(--nr); }
  .status { font-weight: 700; text-transform: uppercase; letter-spacing: .06em; font-size: .85rem; }
  .reading { color: var(--muted); font-size: .88rem; margin: 6px 0 0; }
  .draft { background: var(--card); border: 1px dashed var(--line); padding: 12px 16px;
           font-size: .9rem; color: var(--ink); }
  "

  ledger_rows <- paste0(vapply(audit$ledger, function(l) {
    v <- if (isTRUE(l$tested)) verdict_chip(l$verdict)
         else if (l$status == "assumed") '<span class="meta">untested</span>' else ""
    sprintf("<tr><td><strong>%s</strong><br><span class='meta'>%s</span></td><td>%s</td><td>%s</td><td>%s</td></tr>",
            esc(gsub("_", " ", l$invariance)), esc(l$status),
            esc(l$rationale), esc(l$licenses), v)
  }, character(1)), collapse = "\n")

  test_blocks <- paste0(vapply(audit$tests, function(t) {
    if (!is.null(t$adjustment)) {
      aj <- t$adjustment
      setfmt <- function(x) if (length(x) == 0) "&#8709;" else esc(paste(x, collapse = ", "))
      body <- sprintf("<table>
         <tr><th>exposure &rarr; outcome</th><td>%s &rarr; %s</td></tr>
         <tr><td>adjusted for</td><td>{%s}</td></tr>
         <tr><td>sufficient set (from graph)</td><td>{%s}</td></tr>
         <tr><td>missing (graph says adjust, you did not)</td><td>{%s}</td></tr>
         <tr><td>over-adjustment (descendant of exposure)</td><td>{%s}</td></tr></table>",
        esc(aj$exposure), esc(aj$outcome), setfmt(aj$adjusted), setfmt(aj$sufficient_set),
        setfmt(aj$missing), setfmt(aj$over_adjustment))
      return(sprintf("<h2>attack: %s %s</h2><p class='meta'>probes: %s</p>%s<p class='reading'>%s</p>",
                     esc(gsub("_", " ", t$test)), verdict_chip(t$verdict),
                     esc(gsub("_", " ", t$invariance)), body, esc(t$reading)))
    }
    if (!is.null(t$implications)) {
      chip_of <- c(consistent = "ok", violated = "bad",
                   not_resolvable = "nr", not_testable = "nr")
      rows <- paste0(vapply(t$implications, function(im) {
        val <- if (is.na(im$partial_r)) "&mdash;"
               else sprintf("r = %.3f, p = %s", im$partial_r,
                            if (is.na(im$p_value)) "NA" else formatC(im$p_value, format = "g", digits = 2))
        sprintf("<tr><td>%s</td><td>%s</td><td><span class='chip %s'>%s</span></td></tr>",
                esc(im$claim), val, chip_of[[im$status]], esc(gsub("_", " ", im$status)))
      }, character(1)), collapse = "\n")
      body <- sprintf("<table><tr><th>implied independence</th><th>partial correlation</th><th>outcome</th></tr>%s</table>", rows)
      return(sprintf("<h2>attack: %s %s</h2><p class='meta'>probes: %s</p>%s<p class='reading'>%s</p>",
                     esc(gsub("_", " ", t$test)), verdict_chip(t$verdict),
                     esc(gsub("_", " ", t$invariance)), body, esc(t$reading)))
    }
    if (!is.null(t$autocorrelation)) {
      ac <- t$autocorrelation
      val <- function(v, d=4) if (is.null(v) || is.na(v)) "&mdash;" else formatC(v, format="g", digits=d)
      body <- sprintf("<table>
         <tr><th>Moran's I (residuals)</th><td>%s</td></tr>
         <tr><td>expected under independence</td><td>%s</td></tr>
         <tr><td>z, p</td><td>%s, %s</td></tr>
         <tr><td>weights / residuals</td><td>%s-nearest-neighbour / %s (n = %s)</td></tr></table>",
        val(ac$moran_i), val(ac$expected), val(ac$z), val(ac$p_value),
        val(ac$k, 1), if (is.null(ac$residual_type) || is.na(ac$residual_type)) "&mdash;" else esc(ac$residual_type),
        val(ac$n, 6))
      return(sprintf("<h2>attack: %s %s</h2><p class='meta'>probes: %s</p>%s<p class='reading'>%s</p>",
                     esc(gsub("_", " ", t$test)), verdict_chip(t$verdict),
                     esc(gsub("_", " ", t$invariance)), body, esc(t$reading)))
    }
    if (!is.null(t$scenarios)) {
      sc <- t$scenarios
      rrs <- sort(unique(vapply(sc$cells, function(c) c$rr_uy, numeric(1))))
      dls <- sort(unique(vapply(sc$cells, function(c) c$delta, numeric(1))))
      cellmap <- list()
      for (c in sc$cells) cellmap[[paste0(c$rr_uy, "_", c$delta)]] <- c
      header <- paste0("<tr><th>&Delta; prevalence \\ RR<sub>UY</sub></th>",
                       paste0(sprintf("<th>%.1f</th>", rrs), collapse = ""), "</tr>")
      body <- paste0(vapply(dls, function(dl) {
        cellshtml <- paste0(vapply(rrs, function(rr) {
          c <- cellmap[[paste0(rr, "_", dl)]]
          bg <- if (isTRUE(c$tips)) " style='background:#f3d9d4'" else ""
          sprintf("<td%s>%.2f</td>", bg, exp(c$adjusted_estimate))
        }, character(1)), collapse = "")
        sprintf("<tr><th>%.2f</th>%s</tr>", dl, cellshtml)
      }, character(1)), collapse = "\n")
      tgt <- if (is.na(sc$target)) "no effect (null)" else sprintf("ratio %.2f", sc$target)
      cap <- sprintf("<p class='meta'>adjusted %s (ratio scale) after an unmeasured confounder at prevalence %.2f; shaded cells tip past %s. Plausible bound: RR<sub>UY</sub> &le; %.1f, &Delta; &le; %.2f</p>",
                     esc(a$scale), sc$confounder_prevalence, tgt, sc$plausible_rr_uy, sc$plausible_delta)
      return(sprintf("<h2>attack: %s %s</h2><p class='meta'>probes: %s</p>%s<table>%s%s</table><p class='reading'>%s</p>",
                     esc(gsub("_", " ", t$test)), verdict_chip(t$verdict),
                     esc(gsub("_", " ", t$invariance)), cap, header, body, esc(t$reading)))
    }
    if (!is.null(t$spillover)) {
      sp <- t$spillover
      nb <- if (is.na(sp$neighbor_exposure_coef)) "not estimated" else
        sprintf("%.3f [%.3f, %.3f]", sp$neighbor_exposure_coef, sp$ci_low, sp$ci_high)
      body <- sprintf("<table>
         <tr><th>neighbour-exposure effect</th><td>%s</td></tr>
         <tr><td>exposure estimate (ignoring neighbours)</td><td>%.3f</td></tr>
         <tr><td>exposure estimate (accounting for neighbours)</td><td>%s</td></tr>
         <tr><td>units with &ge;1 neighbour</td><td>%d</td></tr></table>",
        nb, sp$exposure_estimate,
        if (is.na(sp$exposure_estimate_adjusted)) "&mdash;" else sprintf("%.3f", sp$exposure_estimate_adjusted),
        sp$n_with_neighbors)
      return(sprintf("<h2>attack: %s %s</h2><p class='meta'>probes: %s</p>%s<p class='reading'>%s</p>",
                     esc(gsub("_", " ", t$test)), verdict_chip(t$verdict),
                     esc(gsub("_", " ", t$invariance)), body, esc(t$reading)))
    }
    if (!is.null(t$sensitivity)) {
      s <- t$sensitivity
      body <- sprintf(
        "<table><tr><th>quantity</th><th>value</th></tr>
         <tr><td>ratio estimate</td><td>%.2f [%.2f, %.2f]</td></tr>
         <tr><td>E-value (point estimate)</td><td>%.2f</td></tr>
         <tr><td>E-value (interval limit nearest null)</td><td>%s</td></tr>
         <tr><td>plausible confounding benchmark</td><td>%.2f</td></tr></table>",
        s$rr_point, s$rr_ci_low, s$rr_ci_high, s$e_value_point,
        if (isTRUE(all.equal(s$e_value_ci, 1))) "1 (interval includes no effect)"
        else sprintf("%.2f", s$e_value_ci), s$benchmark)
      return(sprintf("<h2>attack: %s %s</h2><p class='meta'>probes: %s</p>%s<p class='reading'>%s</p>",
                     esc(gsub("_", " ", t$test)), verdict_chip(t$verdict),
                     esc(gsub("_", " ", t$invariance)), body, esc(t$reading)))
    }
    rows <- paste0(apply(t$variants, 1, function(r) {
      sprintf("<tr><td>%s</td><td>%s</td><td>[%s, %s]</td><td>%s</td></tr>",
              esc(r[["label"]]), fmt(as.numeric(r[["estimate"]])),
              fmt(as.numeric(r[["ci_low"]])), fmt(as.numeric(r[["ci_high"]])),
              as.integer(r[["n"]]))
    }), collapse = "\n")
    failed <- if (t$n_failed > 0)
      sprintf("<p class='meta'>%d variant refit(s) failed and are not shown.</p>", t$n_failed) else ""
    sprintf("<h2>attack: %s %s</h2>
             <p class='meta'>probes: %s</p>
             <table><tr><th>variant</th><th>estimate</th><th>95%% interval</th><th>n</th></tr>%s</table>
             %s<p class='reading'>%s</p>",
            esc(gsub("_", " ", t$test)), verdict_chip(t$verdict),
            esc(gsub("_", " ", t$invariance)), rows, failed, esc(t$reading))
  }, character(1)), collapse = "\n")

  surface <- if (length(d$exposed_surface) > 0)
    paste0("<p><strong>Exposed surface</strong> (relied on, not settled): ",
           esc(paste(gsub("_", " ", d$exposed_surface), collapse = "; ")), "</p>") else ""
  load_b <- if (length(d$load_bearing) > 0)
    paste0("<p><strong>Load-bearing</strong> (attacked, stable): ",
           esc(paste(gsub("_", " ", d$load_bearing), collapse = "; ")), "</p>") else ""
  broken <- if (!is.null(d$broken_by))
    paste0("<p><strong>Broken by</strong>: ", esc(d$broken_by), "</p>") else ""

  lattice_html <- ""
  L <- audit$lattice
  if (!is.null(L) && length(L$nodes) > 0) {
    chip_of <- c(consistent = "ok", attenuated = "nr", reversed = "bad")
    lrows <- paste0(vapply(L$nodes, function(nd) {
      pooled <- if (length(unlist(nd$pooled))) paste(gsub("_", " ", unlist(nd$pooled)), collapse = ", ") else "nothing"
      sprintf("<tr><td>pool: %s</td><td>%s [%s, %s]</td><td>%d</td><td><span class='chip %s'>%s</span></td></tr>",
              esc(pooled), fmt(nd$estimate), fmt(nd$ci_low), fmt(nd$ci_high), nd$n,
              chip_of[[nd$status]], esc(nd$status))
    }, character(1)), collapse = "\n")
    lattice_html <- sprintf(
      "<h2>assumption lattice %s</h2><p class='meta'>pooling axes: %s (each node pools some axes and stratifies the rest)</p>%s
       <table><tr><th>node</th><th>estimate (%s)</th><th>n</th><th>status</th></tr>%s</table>
       <p class='reading'>%s</p>",
      verdict_chip(L$verdict), esc(paste(gsub("_", " ", L$axes), collapse = ", ")),
      lattice_svg(L), esc(a$scale), lrows, esc(L$reading))
  }

  html <- sprintf("<!doctype html><html><head><meta charset='utf-8'>
<title>structural audit &mdash; %s</title><style>%s</style></head><body><main>
<h1>Structural audit</h1>
<p class='meta'>%s &middot; unit: %s &middot; %s &middot; engine assesslite %s &middot; core spec %s &middot; %s &middot;
 data %d &times; %d, md5 %s</p>

<h2>declared structure</h2>
<table>
<tr><th>cluster</th><td>%s</td></tr>
<tr><th>time</th><td>%s</td></tr>
<tr><th>subgroups</th><td>%s</td></tr>
<tr><th>covariates</th><td>%s</td></tr>
</table>

<h2>invariance ledger</h2>
<table><tr><th>claim</th><th>rationale</th><th>licenses</th><th>verdict</th></tr>%s</table>

<h2>full-sample estimate</h2>
<table><tr><th>scale</th><th>estimate</th><th>95%% interval</th><th>n</th></tr>
<tr><td>%s</td><td>%s</td><td>[%s, %s]</td><td>%d</td></tr></table>

%s

<h2>decision</h2>
<div class='decision %s'><span class='status'>%s</span>
<p>%s</p>%s%s%s</div>

%s

<h2>limitations text (draft)</h2>
<div class='draft'>%s</div>
</main></body></html>",
    esc(a$estimand), css,
    esc(a$estimand), esc(a$unit), esc(a$estimator),
    esc(al$provenance$engine_version), esc(al$provenance$spec_version),
    esc(al$provenance$created),
    al$provenance$data_fingerprint$n_rows, al$provenance$data_fingerprint$n_cols,
    esc(substr(al$provenance$data_fingerprint$md5, 1, 12)),
    esc(if (is.null(s$cluster)) "none declared" else s$cluster),
    esc(if (is.null(s$time)) "none declared" else s$time),
    esc(if (length(s$subgroups) == 0) "none declared" else paste(s$subgroups, collapse = ", ")),
    esc(if (length(a$covariates) == 0) "none" else paste(a$covariates, collapse = ", ")),
    ledger_rows,
    esc(a$scale), fmt(e$value), fmt(e$ci_low), fmt(e$ci_high), e$n,
    test_blocks,
    d$status, toupper(d$status), esc(d$rationale), load_b, surface, broken,
    lattice_html,
    esc(limitations_paragraph(audit)))

  con <- file(path, open = "w", encoding = "UTF-8")
  on.exit(close(con), add = TRUE)
  writeLines(enc2utf8(html), con, useBytes = TRUE)
  invisible(path)
}
